### PR TITLE
Lines

### PR DESCRIPTION
**Pull request by glima**
While packaging Soletta, I noticed that these #line entries fsck big time generating sane debug packages for the js module. This fixes that.

### CODE REVIEW

**Comment by bdilly** [comment]
Honestly I don't like much the idea of changing duktape code in this repository. What are these lines used for?
If unnecessary, a patch could be sent upstream, right?
But if they aren't accepting for stupid reasons I'm ok with this approach.

**Comment by glima** [comment]
I have no idea why they leave these leftovers on the amalgamated file, I guess it's a bug. Ok, I'll try to contact them upstream at some point.

**Comment by glima** [comment]
Upstream devs of duktape have been contacted WRT this and it seems we're getting a release (1.4.0) addressing this. Soon...

**Comment by glima** [comment]
https://github.com/svaarala/duktape/issues/362 and https://github.com/svaarala/duktape/pull/363 are happening, for the record.

**Comment by glima** [comment]
https://github.com/svaarala/duktape/pull/363 got merged. As soon as they have the next release, I'll update on Soletta's side.

**Comment by glima** [comment]
Just as a tip, that release should be 1.4.0 (not issued yet).

**Comment by glima** [comment]
#4 is the new PR for this, closing.

**Pull request closed without merging**
